In [1]:
import numpy as nd
import pandas as pd
from pandas import Series, DataFrame

In [2]:
# Lending_club_data01.csv

In [4]:
loans = pd.read_csv('lending_club_data01.csv')

In [6]:
loans.head()

int_rate  installment  open_acc  revol_bal  revol_util  total_acc  \
0     10.65       162.87         3      13648        83.7          9   
1     15.27        59.83         3       1687         9.4          4   
2     15.96        84.33         2       2956        98.5         10   
3     13.49       339.31        10       5598        21.0         37   
4      7.90       156.46         9       7963        28.3         12   

   bad_loans  grade_num  
0          0          5  
1          1          4  
2          0          4  
3          0          4  
4          0          6

In [7]:
loans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1468 entries, 0 to 1467
Data columns (total 8 columns):
int_rate       1468 non-null float64
installment    1468 non-null float64
open_acc       1468 non-null int64
revol_bal      1468 non-null int64
revol_util     1468 non-null float64
total_acc      1468 non-null int64
bad_loans      1468 non-null int64
grade_num      1468 non-null int64
dtypes: float64(3), int64(5)
memory usage: 91.8 KB


In [8]:
loans.tail()

int_rate  installment  open_acc  revol_bal  revol_util  total_acc  \
1463      6.62       377.66        11      10825        16.1         25   
1464     18.64       360.41         2        564        70.5         19   
1465     16.29       494.21        15      24536        71.7         29   
1466      7.90       500.65         4        404        31.1         12   
1467     15.27       208.79         6        760        69.1         19   

      bad_loans  grade_num  
1463          0          6  
1464          0          2  
1465          0          3  
1466          0          6  
1467          0          4

In [9]:
loans['good_loans'] = loans['bad_loans'].apply(lambda y: 'yes' if y==0 else 'no')

In [10]:
loans.head()

int_rate  installment  open_acc  revol_bal  revol_util  total_acc  \
0     10.65       162.87         3      13648        83.7          9   
1     15.27        59.83         3       1687         9.4          4   
2     15.96        84.33         2       2956        98.5         10   
3     13.49       339.31        10       5598        21.0         37   
4      7.90       156.46         9       7963        28.3         12   

   bad_loans  grade_num good_loans  
0          0          5        yes  
1          1          4         no  
2          0          4        yes  
3          0          4        yes  
4          0          6        yes

In [11]:
X = loans.drop(['bad_loans', 'good_loans'], axis=1)

In [12]:
y = loans['good_loans']

In [13]:
print(X.shape, y.shape)

(1468, 7) (1468,)


In [32]:
from sklearn.model_selection import train_test_split


In [33]:
from sklearn.tree import DecisionTreeClassifier

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state = 124)


In [35]:
print(X_train.shape, X_test.shape)

(1027, 7) (441, 7)


In [36]:
print(y_train.shape, y_test.shape)

(1027,) (441,)


In [37]:
model = DecisionTreeClassifier()

In [38]:
model.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [47]:
predicition = model.predict(X_test)

In [48]:
from sklearn.metrics import classification_report, confusion_matrix

In [49]:
print(confusion_matrix(y_test, prediction))

[[ 17  50]
 [ 63 311]]


In [50]:
print(classification_report(y_test, predicition))

              precision    recall  f1-score   support

          no       0.21      0.25      0.23        67
         yes       0.86      0.83      0.85       374

    accuracy                           0.74       441
   macro avg       0.54      0.54      0.54       441
weighted avg       0.76      0.74      0.75       441



In [51]:
# random Forest classifier

In [52]:
from sklearn.ensemble import RandomForestClassifier

In [53]:
rf_model = RandomForestClassifier(n_estimators = 150)

In [54]:
rf_model.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=150,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [61]:
rf_prediction = rf_model.predict(X_test)

In [62]:
print(classification_report(y_test, rf_prediction))

              precision    recall  f1-score   support

          no       0.33      0.09      0.14        67
         yes       0.86      0.97      0.91       374

    accuracy                           0.83       441
   macro avg       0.59      0.53      0.52       441
weighted avg       0.78      0.83      0.79       441



In [67]:
print(confusion_matrix(y_test, rf_prediction))

[[  6  61]
 [ 12 362]]


In [69]:
loans = pd.read_csv('lending_club_new_data.csv')

In [70]:
loans.head()

loan_amnt  funded_amnt  funded_amnt_inv  int_rate  installment  annual_inc  \
0       5000         5000             4975     10.65       162.87       24000   
1       2500         2500             2500     15.27        59.83       30000   
2       2400         2400             2400     15.96        84.33       12252   
3      10000        10000            10000     13.49       339.31       49200   
4       5000         5000             5000      7.90       156.46       36000   

     dti  delinq_2yrs  inq_last_6mths  open_acc  ...  total_rec_late_fee  \
0  27.65            0               1         3  ...                0.00   
1   1.00            0               5         3  ...                0.00   
2   8.72            0               2         2  ...                0.00   
3  20.00            0               1        10  ...               16.97   
4  11.20            0               3         9  ...                0.00   

   recoveries  collection_recovery_fee  last_pymnt_amnt  bad_loans  \
0        0.00                     0.00           171.62          0   
1      117.08                     1.11           119.66          1   
2        0.00                     0.00           649.91          0   
3        0.00                     0.00           357.48          0   
4        0.00                     0.00           161.03          0   

   emp_length_num  grade_num  sub_grade_num  delinq_2yrs_zero  \
0              11          5            0.4                 1   
1               1          4            0.8                 1   
2              11          4            1.0                 1   
3              11          4            0.2                 1   
4               4          6            0.8                 1   

   payment_inc_ratio  
0            8.14350  
1            2.39320  
2            8.25955  
3            8.27585  
4            5.21533  

[5 rows x 24 columns]

In [71]:
loans.tail()

loan_amnt  funded_amnt  funded_amnt_inv  int_rate  installment  \
9511       6000         6000             6000     23.40       170.53   
9512      15250        15250            15250     17.57       548.05   
9513       8525         8525             8525     18.25       217.65   
9514      22000        22000            22000     19.97       582.50   
9515       2000         2000             2000      7.90        62.59   

      annual_inc    dti  delinq_2yrs  inq_last_6mths  open_acc  ...  \
9511       45600   1.50            1               0         3  ...   
9512       65000  11.26            1               2         8  ...   
9513       37536  12.28            4               0        12  ...   
9514       78000  18.45            0               5        18  ...   
9515       83000   5.39            3               1        21  ...   

      total_rec_late_fee  recoveries  collection_recovery_fee  \
9511                 0.0         0.0                    0.000   
9512                 0.0         0.0                    0.000   
9513                 0.0      1159.4                   11.594   
9514                 0.0         0.0                    0.000   
9515                 0.0         0.0                    0.000   

      last_pymnt_amnt  bad_loans  emp_length_num  grade_num  sub_grade_num  \
9511           170.53          1               0          2            1.0   
9512         14810.30          0              11          3            0.4   
9513           217.65          1               6          3            0.6   
9514            17.50          1              11          3            1.0   
9515          1500.68          0               4          6            0.8   

      delinq_2yrs_zero  payment_inc_ratio  
9511                 0           4.487630  
9512                 0          10.117800  
9513                 0           6.958120  
9514                 1           8.961540  
9515                 0           0.904916  

[5 rows x 24 columns]

In [72]:
loans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9516 entries, 0 to 9515
Data columns (total 24 columns):
loan_amnt                  9516 non-null int64
funded_amnt                9516 non-null int64
funded_amnt_inv            9516 non-null int64
int_rate                   9516 non-null float64
installment                9516 non-null float64
annual_inc                 9516 non-null int64
dti                        9516 non-null float64
delinq_2yrs                9516 non-null int64
inq_last_6mths             9516 non-null int64
open_acc                   9516 non-null int64
total_pymnt                9516 non-null float64
total_pymnt_inv            9516 non-null float64
total_rec_prncp            9516 non-null float64
total_rec_int              9516 non-null float64
total_rec_late_fee         9516 non-null float64
recoveries                 9516 non-null float64
collection_recovery_fee    9516 non-null float64
last_pymnt_amnt            9516 non-null float64
bad_loans                

In [73]:
loans['good_loans'] = loans['bad_loans'].apply(lambda y: 'yes' if y==0 else 'no')

In [74]:
loans.head()

loan_amnt  funded_amnt  funded_amnt_inv  int_rate  installment  annual_inc  \
0       5000         5000             4975     10.65       162.87       24000   
1       2500         2500             2500     15.27        59.83       30000   
2       2400         2400             2400     15.96        84.33       12252   
3      10000        10000            10000     13.49       339.31       49200   
4       5000         5000             5000      7.90       156.46       36000   

     dti  delinq_2yrs  inq_last_6mths  open_acc  ...  recoveries  \
0  27.65            0               1         3  ...        0.00   
1   1.00            0               5         3  ...      117.08   
2   8.72            0               2         2  ...        0.00   
3  20.00            0               1        10  ...        0.00   
4  11.20            0               3         9  ...        0.00   

   collection_recovery_fee  last_pymnt_amnt  bad_loans  emp_length_num  \
0                     0.00           171.62          0              11   
1                     1.11           119.66          1               1   
2                     0.00           649.91          0              11   
3                     0.00           357.48          0              11   
4                     0.00           161.03          0               4   

   grade_num  sub_grade_num  delinq_2yrs_zero  payment_inc_ratio  good_loans  
0          5            0.4                 1            8.14350         yes  
1          4            0.8                 1            2.39320          no  
2          4            1.0                 1            8.25955         yes  
3          4            0.2                 1            8.27585         yes  
4          6            0.8                 1            5.21533         yes  

[5 rows x 25 columns]

In [75]:
X = loans.drop(['bad_loans', 'good_loans'], axis = 1)

In [76]:
y = loans['good_loans']

In [77]:
print(X.shape, y.shape)

(9516, 23) (9516,)


In [78]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 124)

In [79]:
print(X_train.shape, X_test.shape)

(6661, 23) (2855, 23)


In [80]:
print(y_train.shape, y_test.shape)

(6661,) (2855,)


In [81]:
model2 = DecisionTreeClassifier()

In [82]:
model2.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [85]:
prediction2 = model2.predict(X_test)

In [86]:
print(confusion_matrix(y_test, prediction2))

[[ 444   11]
 [   4 2396]]


In [87]:
print(classification_report(y_test, prediction2))

              precision    recall  f1-score   support

          no       0.99      0.98      0.98       455
         yes       1.00      1.00      1.00      2400

    accuracy                           0.99      2855
   macro avg       0.99      0.99      0.99      2855
weighted avg       0.99      0.99      0.99      2855



In [88]:
# random forest 

In [89]:
rf_model2 = RandomForestClassifier(n_estimators = 150)

In [90]:
rf_model.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=150,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [91]:
rf_prediction = rf_model.predict(X_test)

In [94]:
print(confusion_matrix(y_test, rf_prediction))

[[ 442   13]
 [   0 2400]]


In [96]:
print(classification_report(y_test, rf_prediction))

              precision    recall  f1-score   support

          no       1.00      0.97      0.99       455
         yes       0.99      1.00      1.00      2400

    accuracy                           1.00      2855
   macro avg       1.00      0.99      0.99      2855
weighted avg       1.00      1.00      1.00      2855



In [99]:
print(classification_report(y_test, prediction2))  # comparison 

              precision    recall  f1-score   support

          no       0.99      0.98      0.98       455
         yes       1.00      1.00      1.00      2400

    accuracy                           0.99      2855
   macro avg       0.99      0.99      0.99      2855
weighted avg       0.99      0.99      0.99      2855



In [100]:
loans.head()

loan_amnt  funded_amnt  funded_amnt_inv  int_rate  installment  annual_inc  \
0       5000         5000             4975     10.65       162.87       24000   
1       2500         2500             2500     15.27        59.83       30000   
2       2400         2400             2400     15.96        84.33       12252   
3      10000        10000            10000     13.49       339.31       49200   
4       5000         5000             5000      7.90       156.46       36000   

     dti  delinq_2yrs  inq_last_6mths  open_acc  ...  recoveries  \
0  27.65            0               1         3  ...        0.00   
1   1.00            0               5         3  ...      117.08   
2   8.72            0               2         2  ...        0.00   
3  20.00            0               1        10  ...        0.00   
4  11.20            0               3         9  ...        0.00   

   collection_recovery_fee  last_pymnt_amnt  bad_loans  emp_length_num  \
0                     0.00           171.62          0              11   
1                     1.11           119.66          1               1   
2                     0.00           649.91          0              11   
3                     0.00           357.48          0              11   
4                     0.00           161.03          0               4   

   grade_num  sub_grade_num  delinq_2yrs_zero  payment_inc_ratio  good_loans  
0          5            0.4                 1            8.14350         yes  
1          4            0.8                 1            2.39320          no  
2          4            1.0                 1            8.25955         yes  
3          4            0.2                 1            8.27585         yes  
4          6            0.8                 1            5.21533         yes  

[5 rows x 25 columns]

In [106]:
X = loans.drop(['bad_loans','good_loans','annual_inc','dti','delinq_2yrs','inq_last_6mths','open_acc','total_pymnt','total_pymnt','total_pymnt_inv','total_rec_prncp','total_rec_int','total_rec_late_fee','recoveries','collection_recovery_fee'], axis=1)

In [108]:
y = loans['good_loans']

In [109]:
print(X.shape, y.shape)

(9516, 11) (9516,)


In [112]:
X_train, X_test, y_train, t_test = train_test_split(X,y, test_size=0.3, random_state=124)

In [113]:
print(X_train.shape, X_test.shape)

(6661, 11) (2855, 11)


In [114]:
print(y_train.shape, y_test.shape)

(6661,) (2855,)


In [115]:
model3 = DecisionTreeClassifier()

In [116]:
model3.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [119]:
prediction3 = model3.predict(X_test)

In [120]:
print(confusion_matrix(y_test, prediction3))

[[ 307  148]
 [ 168 2232]]


In [123]:
print(classification_report(y_test, prediction3))

              precision    recall  f1-score   support

          no       0.65      0.67      0.66       455
         yes       0.94      0.93      0.93      2400

    accuracy                           0.89      2855
   macro avg       0.79      0.80      0.80      2855
weighted avg       0.89      0.89      0.89      2855



In [124]:
# Random Forest

In [125]:
rf_model3 = RandomForestClassifier(n_estimators=150)

In [127]:
rf_model3.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=150,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [132]:
rf_prediction3 = rf_model3.predict(X_test)

In [133]:
print(confusion_matrix(y_test, rf_prediction3))

[[ 281  174]
 [  78 2322]]


In [134]:
print(classification_report(y_test, rf_prediction3))

              precision    recall  f1-score   support

          no       0.78      0.62      0.69       455
         yes       0.93      0.97      0.95      2400

    accuracy                           0.91      2855
   macro avg       0.86      0.79      0.82      2855
weighted avg       0.91      0.91      0.91      2855

